meters:
  - meter_id: M1
    video_device: /dev/v4l/by-id/usb-046d_B525_HD_Webcam_63928130-video-index0
    focus: 20
    aligned_width: 500
    aligned_height: 120
    threshold_mode: otsu
    invert_binary: true
    perspective_src_points:   # mutually exclusive with crop_source_box
      - [927, 674]             # top-left
      - [1172, 672]             # top-right
      - [1173, 713]            # bottom-right
      - [925, 716]            # bottom-left    max_translation_px: 4
    inner_pad_x: 2
    inner_pad_y: 2
    digit_boxes:
      - { x: 0,   y: 0, w: 60, h: 120 }
      - { x: 106,  y: 0, w: 60, h: 120 }
      - { x: 212, y: 0, w: 60, h: 120 }
      - { x: 322, y: 0, w: 60, h: 120 }
      - { x: 434, y: 0, w: 60, h: 120 }

  - meter_id: M2
    video_device: /dev/v4l/by-id/usb-046d_B525_HD_Webcam_7AAA8130-video-index0
    focus: 60
    aligned_width: 500
    aligned_height: 120
    threshold_mode: otsu
    invert_binary: true
    perspective_src_points:
      - [767, 587]             # top-left
      - [1003, 575]             # top-right
      - [1005, 616]             # bottom-right
      - [766, 629]             # bottom-left
    max_translation_px: 4
    inner_pad_x: 2
    inner_pad_y: 2
    digit_boxes:
      - { x: 0,   y: 0, w: 60, h: 120 }
      - { x: 106,  y: 0, w: 60, h: 120 }
      - { x: 212, y: 0, w: 60, h: 120 }
      - { x: 322, y: 0, w: 60, h: 120 }
      - { x: 434, y: 0, w: 60, h: 120 }

  - meter_id: M3
    video_device: /dev/v4l/by-id/usb-046d_B525_HD_Webcam_7FDE8130-video-index0
    focus: 55
    aligned_width: 500
    aligned_height: 120
    threshold_mode: otsu
    invert_binary: true
    perspective_src_points:
      - [736, 640]             # top-left
      - [967, 636]             # top-right
      - [970, 675]             # bottom-right
      - [735, 682]             # bottom-left
    max_translation_px: 4
    inner_pad_x: 2
    inner_pad_y: 2
    digit_boxes:
      - { x: 0,   y: 0, w: 60, h: 120 }
      - { x: 106,  y: 0, w: 60, h: 120 }
      - { x: 212, y: 0, w: 60, h: 120 }
      - { x: 322, y: 0, w: 60, h: 120 }
      - { x: 434, y: 0, w: 60, h: 120 }
